=== TIBCOSoftware/fabrician-oracle-coherence-enabler/src/main/resources/content/config/coherence-report-group-config.xsd
<?xml version="1.0"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xmlns.oracle.com/coherence/coherence-report-group-config"
            xmlns="http://xmlns.oracle.com/coherence/coherence-report-group-config"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.0">

    <xsd:annotation>
        <xsd:documentation>
            Copyright (c) 2000, 2011, Oracle and/or its affiliates. All rights reserved.

            Oracle is a registered trademarks of Oracle Corporation and/or its
            affiliates.

            This software is the confidential and proprietary information of
            Oracle Corporation. You shall not disclose such confidential and
            proprietary information and shall use it only in accordance with the
            terms of the license agreement you entered into with Oracle.

            This notice may not be removed or altered.     
        </xsd:documentation>
    </xsd:annotation>

    <xsd:annotation>
        <xsd:documentation>
            This is the XML Schema Definition for the report-group.xml configuration
            file.
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="report-group">
        <xsd:annotation>
            <xsd:documentation>
                The report-group element is the root element of the report-group
                descriptor.

                Used in: n/a
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="frequency" />
                <xsd:element ref="output-directory" minOccurs="0" />
                <xsd:element ref="report-list" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="frequency">
        <xsd:annotation>
            <xsd:documentation>
                The frequency element is the duration between each execution of the
                reports in
                the report list.

                Used in: report-group
            </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:pattern value="(\d)+(S|s|M|m)?" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="output-directory" type="xsd:string">
        <xsd:annotation>
            <xsd:documentation>
                The output-directory element is the location for the output files.

                Used in: report-group
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:element name="report-list">
        <xsd:annotation>
            <xsd:documentation>
                The report-list element contains a list of report configurations.

                Used in: report-group
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="report-config" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="report-config">
        <xsd:annotation>
            <xsd:documentation>
                The report-config element contains the report configuration location
                and
                corresponding initialization parameters.

                Used in: report-group
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="location" />
                <xsd:element ref="init-params" minOccurs="0" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="init-params">
        <xsd:annotation>
            <xsd:documentation>
                The init-params element contains a list of initialization parameters.

                Used in: report-config
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="init-param" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="init-param">
        <xsd:annotation>
            <xsd:documentation>
                The init-param element contains an initialization parameter for a
                report.

                Used in: init-params
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice>
                    <xsd:element ref="param-name" />
                    <xsd:element ref="param-type" />
                </xsd:choice>
                <xsd:element ref="param-value" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="param-name" type="xsd:string">
        <xsd:annotation>
            <xsd:documentation>
                The param-name element specifies the name of the initialization
                parameter.

                Used in: init-param
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:element name="param-type">
        <xsd:annotation>
            <xsd:documentation>
                The param-type element specifies the Java type of the initialization
                parameter.

                Supported types are:
                - string - indicates that the value is a java.lang.String
                - long - indicates that the value is a java.lang.Long
                - double -
                indicates that the value is a java.lang.Double

                Used in: init-param
            </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="string" />
                <xsd:enumeration value="java.lang.String" />
                <xsd:enumeration value="long" />
                <xsd:enumeration value="java.lang.Long" />
                <xsd:enumeration value="double" />
                <xsd:enumeration value="java.lang.Double" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="param-value" type="xsd:string">
        <xsd:annotation>
            <xsd:documentation>
                The param-value element specifies a value of the initialization
                parameter.

                The value is in a format specific to the type of the parameter.

                Used in: init-param
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:element name="location" type="xsd:string">
        <xsd:annotation>
            <xsd:documentation>
                The location element contains a path to a report configuration
                descriptor that
                conforms to the report-config.dtd. This path could be either a file or a
                URL.

                Used in: report-list
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>
</xsd:schema>

=== TIBCOSoftware/fabrician-oracle-coherence-enabler/src/main/resources/content/config/reports/report-group.xml
<report-group xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xmlns="http://xmlns.oracle.com/coherence/coherence-report-group-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-report-group-config coherence-report-group-config.xsd">

  <frequency>1m</frequency>
  <output-directory>./</output-directory>
  <report-list>
    <report-config>
      <location>reports/report-node.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-network-health.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-network-health-detail.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-memory-status.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-service.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-cache-effectiveness.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-proxy.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-management.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-flashjournal.xml</location>
    </report-config>
    <report-config>
      <location>reports/report-ramjournal.xml</location>
    </report-config>
  </report-list>
</report-group>
